language: python
python:
  - "3.6"

sudo: false
dist: trusty

install: "pip install -r requirements.txt"

before_script: 
  - chmod 755 test/test.py
  - 

script: test/test.py

notifications: 
  email: false